language: scala
dist: xenial

env:
  global:
    - JAVA_OPTS: -Xss4m

jobs:
  include:
    - stage: formatting
      if: type = pull_request
      script:
        - ./millw __.reformat
        - git diff --exit-code --name-status
        - if [[ $(git diff --exit-code --name-status) ]]; then echo 'Your code is not formatted correctly, please format it, check it and push formatted code'; exit 1; fi
    - stage: test
      script:
        - ./millw runtime.compile
        - ./millw all core.test runtime.test
    - script:
        - ./millw runtime.compile
        - ./millw examples.mdoc
    - stage: deploy
      script: skip
      if: type != pull_request AND tag IS present
      before_deploy:
        - gem install nanoc kramdown-parser-gfm rouge
        - git config --global user.email "$USER_EMAIL"
        - git config --global user.name "$USER_NAME"
      deploy:
        - provider: releases
          token: $GH_TOKEN
          name: $TRAVIS_TAG
          edge: true
          on:
            tags: true
            all_branches: true
        - provider: script
          script: bash scripts/publish_github_pages.sh
          cleanup: true
          edge: true
          on:
            tags: true
            all_branches: true
        - provider: script
          script: bash scripts/publish_maven.sh
          cleanup: true
          edge: true
          on:
            tags: true
            all_branches: true

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download

jdk:
  - openjdk11

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+(-.*)?$/
